# Features Scalling 

    Types of Features scalling :
    1. Normalization (L2 Norm)
    2. Standard Scaling

In [3]:
from sklearn.preprocessing import Normalizer 
import pandas as pd

In [4]:
d={
    "Age":[25,30,35,40],
    "Salary":[30000,40000,50000,60000]
}
df=pd.DataFrame(d)
df

   Age  Salary
0   25   30000
1   30   40000
2   35   50000
3   40   60000

# Normalizer

In [10]:
ns=Normalizer()
v1=ns.fit_transform(df)
df1=pd.DataFrame(v1,columns=["Scaled_age","Scaled_salary"])
df1

   Scaled_age  Scaled_salary
0    0.000833            1.0
1    0.000750            1.0
2    0.000700            1.0
3    0.000667            1.0

# Standard Scaling

In [11]:
from sklearn.preprocessing import StandardScaler

In [21]:
sc=StandardScaler()
v2=sc.fit_transform(df)
df2=pd.DataFrame(v2,columns=["Scaled_age","Scaled_salary"])

pd.concat([df1,df2],axis=1)

   Scaled_age  Scaled_salary  Scaled_age  Scaled_salary
0    0.000833            1.0   -1.341641      -1.341641
1    0.000750            1.0   -0.447214      -0.447214
2    0.000700            1.0    0.447214       0.447214
3    0.000667            1.0    1.341641       1.341641