In [1]:
from sklearn.preprocessing import LabelEncoder 
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Qspider\datasets\Data-Analysis-Datasets\Datasets-Practice\titanic.csv")
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [3]:
label=LabelEncoder()
df["Encoded_name"]=label.fit_transform(df["name"])
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,Encoded_name
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,21
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,23
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,24
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,25
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,26
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0,1291
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0,1292
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0,1293
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0,1294
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0,1295

In [ ]:
# Surname of the name column 

surname=df["name"].str.split(",").str[0]
sur=pd.DataFrame(surname)

sur["label_encoding"]=label.fit_transform(sur["name"])

sur["name"]
# surname

<class 'pandas.Series'>
RangeIndex: 1309 entries, 0 to 1308
Series name: name
Non-Null Count  Dtype
--------------  -----
1309 non-null   object
dtypes: object(1)
memory usage: 10.4+ KB

In [40]:
# Title of name column 

title=df["name"].str.split(",").str[1].str.split(".").str[0]
tit=pd.DataFrame(title,columns=["title"])

tit["label_encoding"]=label.fit_transform(tit["title"])
tit

Empty DataFrame
Columns: [title, label_encoding]
Index: []