Learn all things in the Pandas Library

In [21]:
import numpy as np
import pandas as pd

In [22]:
# import the csv file to explore 
df=pd.read_csv("EMP_Table.csv")
df

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30
3    7566   JONES    MANAGER  7839  02-Apr-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10

In [23]:
df.head() # use for to fetch top five rows.
df.tail()  # use for to fetch bottom five rows.

    EMPNO   ENAME       JOB   MGR   HIREDATE   SAL  COMM  DEPTNO
9    7844  TURNER  SALESMAN  7698  08-Sep-81  1500   0.0      30
10   7876   ADAMS     CLERK  7788  23-May-87  1100   NaN      20
11   7900   JAMES     CLERK  7698  03-Dec-81   950   NaN      30
12   7902    FORD   ANALYST  7566  03-Dec-81  3000   NaN      20
13   7934  MILLER     CLERK  7782  23-Jan-82  1300   NaN      10

In [24]:
df.info() # To get the information about the table just like column details 
# df.describe() # It is used to desccribe the table about cout, mean etc about all the statistical things in the table but it is apply only on the numerical column if you want to apply this all the column , you must use "include =all " as a argumrnt in the function.

df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EMPNO     14 non-null     int64
 1   ENAME     14 non-null     str
 2   JOB       14 non-null     str
 3   MGR       14 non-null     int64
 4   HIREDATE  14 non-null     str
 5   SAL       14 non-null     int64
 6   COMM      4 non-null      float64
 7   DEPTNO    14 non-null     int64
dtypes: float64(1), int64(4), str(3)
memory usage: 1.0 KB

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
count,14.000000,14,14,14.000000,14,14.000000,4.000000,14.000000
unique,NaN,14,5,NaN,13,NaN,NaN,NaN
top,NaN,SMITH,CLERK,NaN,03-Dec-81,NaN,NaN,NaN
freq,NaN,1,4,NaN,2,NaN,NaN,NaN
mean,7726.571429,NaN,NaN,7186.500000,NaN,2073.214286,550.000000,22.142857
std,178.294361,NaN,NaN,2070.815809,NaN,1182.503224,602.771377,8.017837
min,7369.000000,NaN,NaN,0.000000,NaN,800.000000,0.000000,10.000000
25%,7588.000000,NaN,NaN,7698.000000,NaN,1250.000000,225.000000,20.000000
50%,7785.000000,NaN,NaN,7698.000000,NaN,1550.000000,400.000000,20.000000
75%,7868.000000,NaN,NaN,7826.250000,NaN,2943.750000,725.000000,30.000000
max,7934.000000,NaN,NaN,7902.000000,NaN,5000.000000,1400.000000,30.000000

In [25]:
df.dtypes # it is used to see the type of the each column which is present inside the table.
df.dtypes=="object"

EMPNO       False
ENAME       False
JOB         False
MGR         False
HIREDATE    False
SAL         False
COMM        False
DEPTNO      False
dtype: bool

In [26]:
# If you want to fetfch only same datatype column then 
df[df.dtypes[df.dtypes=="str"].index]

     ENAME        JOB   HIREDATE
0    SMITH      CLERK  17-Dec-80
1    ALLEN   SALESMAN  20-Feb-81
2     WARD   SALESMAN  22-Feb-81
3    JONES    MANAGER  02-Apr-81
4   MARTIN   SALESMAN  28-Sep-81
5    BLAKE    MANAGER  01-May-81
6    CLARK    MANAGER  09-Jun-81
7    SCOTT    ANALYST  19-Apr-87
8     KING  PRESIDENT  17-Nov-81
9   TURNER   SALESMAN  08-Sep-81
10   ADAMS      CLERK  23-May-87
11   JAMES      CLERK  03-Dec-81
12    FORD    ANALYST  03-Dec-81
13  MILLER      CLERK  23-Jan-82

In [27]:
# You see all the only columns names 
df.columns

Index(['EMPNO', 'ENAME', 'JOB', 'MGR', 'HIREDATE', 'SAL', 'COMM', 'DEPTNO'], dtype='str')

In [28]:
# You can also see particular column from the table 
df[["ENAME","JOB"]]

     ENAME        JOB
0    SMITH      CLERK
1    ALLEN   SALESMAN
2     WARD   SALESMAN
3    JONES    MANAGER
4   MARTIN   SALESMAN
5    BLAKE    MANAGER
6    CLARK    MANAGER
7    SCOTT    ANALYST
8     KING  PRESIDENT
9   TURNER   SALESMAN
10   ADAMS      CLERK
11   JAMES      CLERK
12    FORD    ANALYST
13  MILLER      CLERK

In [29]:
# IN Pandas, we can use slicing concept we fetch the index value as well

df[["ENAME","JOB"]][13:6:-1]
df[::-1]

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30
3    7566   JONES    MANAGER  7839  02-Apr-81  2975     NaN      20
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20

In [30]:
# IF YOU WANT TO CREATE NEW COLUMN IN EXISTING TABLE 
df["DNAME"]="NULL"
df

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO DNAME
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20  NULL
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30  NULL
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30  NULL
3    7566   JONES    MANAGER  7839  02-Apr-81  2975     NaN      20  NULL
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30  NULL
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30  NULL
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10  NULL
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20  NULL
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10  NULL
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30  NULL
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20  NULL
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30  NULL
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20  NULL
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10  NULL

In [31]:
# ALLOCATE THE  COLUMN USING INSERT FUNCTION 
df.insert(loc=3,column="CITY",value="FINANCE")

In [32]:
df.drop(columns=["CITY","DNAME"],inplace=True) # It is used to delete columns from the table permanently.
df

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30
3    7566   JONES    MANAGER  7839  02-Apr-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10

In [33]:
# If you want to delete particular row from the table then 
df.drop(3,axis=0)

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10

In [34]:
# Now we creating our own data 
l=["a1","a2","a3","a4","a5"]
pd.Series(l) # this is the series.

0    a1
1    a2
2    a3
3    a4
4    a5
dtype: str

In [35]:
m1=pd.Series([100,200,300,400,500],index=[1,2,3,4,5]) # series 1
m2=pd.Series([600,700,800,900,1000],index=[6,7,8,9,10]) # Series 2

In [36]:
# Now we can concatenate both the series into single series 
m3=pd.concat([m1,m2])

In [37]:
m3

1      100
2      200
3      300
4      400
5      500
6      600
7      700
8      800
9      900
10    1000
dtype: int64

Dictionary into DataFrame

In [38]:
d={
    "key1":[1,2,3,4,5],
    "key2":[6,7,8,9,10],
    "key3":[11,12,13,14,15]
}

pd.DataFrame(d)

   key1  key2  key3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

In [39]:
# if you want to change the index value then 
d={
    "key1":[1,2,3,4,5],
    "key2":[6,7,8,9,10],
    "key3":[11,12,13,14,15]
}

pd.DataFrame(d,index=["one","Two","three","four","five"])

       key1  key2  key3
one       1     6    11
Two       2     7    12
three     3     8    13
four      4     9    14
five      5    10    15

In [40]:
# If you want to replace the null value to some value, then 
df.fillna("Amandeep") # it is temperory
df.fillna("value",inplace=True) # it is permanent change

TypeError: Invalid value 'value' for dtype 'float64'

In [ ]:
# IF you want to create a table with the some random values for your series and dataframe.
s=pd.Series(np.random.rand(34))
s

0     0.675942
1     0.676676
2     0.464512
3     0.922040
4     0.523054
5     0.997669
6     0.904545
7     0.764693
8     0.267596
9     0.442697
10    0.350017
11    0.187453
12    0.705760
13    0.533434
14    0.685637
15    0.766457
16    0.951295
17    0.650328
18    0.826789
19    0.556693
20    0.316528
21    0.639533
22    0.353284
23    0.390527
24    0.236480
25    0.261104
26    0.079156
27    0.366225
28    0.194194
29    0.156573
30    0.924192
31    0.193827
32    0.764291
33    0.391676
dtype: float64

In [ ]:
# IF you want to create a table with the some random values for your  dataframe.
s=pd.DataFrame(np.random.rand(300,5))
s

            0         1         2         3         4
0    0.645577  0.949186  0.691405  0.777283  0.510814
1    0.775975  0.716147  0.788806  0.691943  0.047640
2    0.727721  0.164391  0.278109  0.191984  0.441365
3    0.048187  0.744287  0.140223  0.693886  0.707699
4    0.458334  0.513046  0.334458  0.292335  0.716158
..        ...       ...       ...       ...       ...
295  0.631608  0.640460  0.734023  0.810316  0.062671
296  0.534331  0.550423  0.544158  0.793346  0.818236
297  0.319562  0.049589  0.217810  0.629831  0.202999
298  0.220404  0.565415  0.671744  0.189025  0.283484
299  0.970502  0.940399  0.693204  0.415641  0.427268

[300 rows x 5 columns]

In [ ]:
# if you want to covert dataframe into numpy 
df.to_numpy()

array([[7369, 'SMITH', 'CLERK', 7902, '17-Dec-80', 800, nan, 20],
       [7499, 'ALLEN', 'SALESMAN', 7698, '20-Feb-81', 1600, 300.0, 30],
       [7521, 'WARD', 'SALESMAN', 7698, '22-Feb-81', 1250, 500.0, 30],
       [7566, 'JONES', 'MANAGER', 7839, '02-Apr-81', 2975, nan, 20],
       [7654, 'MARTIN', 'SALESMAN', 7698, '28-Sep-81', 1250, 1400.0, 30],
       [7698, 'BLAKE', 'MANAGER', 7839, '01-May-81', 2850, nan, 30],
       [7782, 'CLARK', 'MANAGER', 7839, '09-Jun-81', 2450, nan, 10],
       [7788, 'SCOTT', 'ANALYST', 7566, '19-Apr-87', 3000, nan, 20],
       [7839, 'KING', 'PRESIDENT', 0, '17-Nov-81', 5000, nan, 10],
       [7844, 'TURNER', 'SALESMAN', 7698, '08-Sep-81', 1500, 0.0, 30],
       [7876, 'ADAMS', 'CLERK', 7788, '23-May-87', 1100, nan, 20],
       [7900, 'JAMES', 'CLERK', 7698, '03-Dec-81', 950, nan, 30],
       [7902, 'FORD', 'ANALYST', 7566, '03-Dec-81', 3000, nan, 20],
       [7934, 'MILLER', 'CLERK', 7782, '23-Jan-82', 1300, nan, 10]],
      dtype=object)

In [ ]:
# You can transpose your rows into columns 

df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
EMPNO,7369,7499,7521,7566,7654,7698,7782,7788,7839,7844,7876,7900,7902,7934
ENAME,SMITH,ALLEN,WARD,JONES,MARTIN,BLAKE,CLARK,SCOTT,KING,TURNER,ADAMS,JAMES,FORD,MILLER
JOB,CLERK,SALESMAN,SALESMAN,MANAGER,SALESMAN,MANAGER,MANAGER,ANALYST,PRESIDENT,SALESMAN,CLERK,CLERK,ANALYST,CLERK
MGR,7902,7698,7698,7839,7698,7839,7839,7566,0,7698,7788,7698,7566,7782
HIREDATE,17-Dec-80,20-Feb-81,22-Feb-81,02-Apr-81,28-Sep-81,01-May-81,09-Jun-81,19-Apr-87,17-Nov-81,08-Sep-81,23-May-87,03-Dec-81,03-Dec-81,23-Jan-82
SAL,800,1600,1250,2975,1250,2850,2450,3000,5000,1500,1100,950,3000,1300
COMM,NaN,300.0,500.0,NaN,1400.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
DEPTNO,20,30,30,20,30,30,10,20,10,30,20,30,20,10

In [ ]:
#  You can sort your data according to ascending or descending order.

# df.sort_index(axis=0,ascending=False) # sorting according to X-axis 

df.sort_index(axis=1,ascending=False)  # sorting according to Y-axis

     SAL   MGR        JOB   HIREDATE   ENAME  EMPNO  DEPTNO    COMM
0    800  7902      CLERK  17-Dec-80   SMITH   7369      20     NaN
1   1600  7698   SALESMAN  20-Feb-81   ALLEN   7499      30   300.0
2   1250  7698   SALESMAN  22-Feb-81    WARD   7521      30   500.0
3   2975  7839    MANAGER  02-Apr-81   JONES   7566      20     NaN
4   1250  7698   SALESMAN  28-Sep-81  MARTIN   7654      30  1400.0
5   2850  7839    MANAGER  01-May-81   BLAKE   7698      30     NaN
6   2450  7839    MANAGER  09-Jun-81   CLARK   7782      10     NaN
7   3000  7566    ANALYST  19-Apr-87   SCOTT   7788      20     NaN
8   5000     0  PRESIDENT  17-Nov-81    KING   7839      10     NaN
9   1500  7698   SALESMAN  08-Sep-81  TURNER   7844      30     0.0
10  1100  7788      CLERK  23-May-87   ADAMS   7876      20     NaN
11   950  7698      CLERK  03-Dec-81   JAMES   7900      30     NaN
12  3000  7566    ANALYST  03-Dec-81    FORD   7902      20     NaN
13  1300  7782      CLERK  23-Jan-82  MILLER   7934      10     NaN

In [ ]:
# You can also copy your data into another variable 
newdf=df.copy()
newdf

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30
3    7566   JONES    MANAGER  7839  02-Apr-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10

In [ ]:
# there is another way to create a copy your dataframe into another variable but there is one different that whenever you change in new variable then it will also impact on the old dataframe. while when you use copy() function , this thing is not  happen there.
newdf1=df
newdf1

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30
3    7566   JONES    MANAGER  7839  02-Apr-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10

In [ ]:
# if you want to see particular sction of the dataframe.
df.loc[0] # df.loc["row"]
df.loc[2,"JOB"] # df.loc["row","column"]
df.loc[[0,12,13],["EMPNO","JOB","SAL"]] # df.loc[["row1","row2","row2",---],["col1","col2","col3",---]]
df.loc[0:12,"EMPNO":"SAL"]

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL
0    7369   SMITH      CLERK  7902  17-Dec-80   800
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250
3    7566   JONES    MANAGER  7839  02-Apr-81  2975
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250
5    7698   BLAKE    MANAGER  7839  01-May-81  2850
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000
8    7839    KING  PRESIDENT     0  17-Nov-81  5000
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500
10   7876   ADAMS      CLERK  7788  23-May-87  1100
11   7900   JAMES      CLERK  7698  03-Dec-81   950
12   7902    FORD    ANALYST  7566  03-Dec-81  3000

In [ ]:
# we can give also condition in the column 
# df.loc[(df["SAL"]>2000)] # SINGLE CONDITON 
df.loc[(df["SAL"]>2000)&(df["JOB"]=="MANAGER")] # MULTIPLE CONDITION

   EMPNO  ENAME      JOB   MGR   HIREDATE   SAL  COMM  DEPTNO
3   7566  JONES  MANAGER  7839  02-Apr-81  2975   NaN      20
5   7698  BLAKE  MANAGER  7839  01-May-81  2850   NaN      30
6   7782  CLARK  MANAGER  7839  09-Jun-81  2450   NaN      10

In [50]:
# if you want to check the how many null values are present in the table 
df.isnull().sum()

EMPNO        0
ENAME        0
JOB          0
MGR          0
HIREDATE     0
SAL          0
COMM        10
DEPTNO       0
dtype: int64

In [53]:
# if you want to see how many duplicates values in particular column 
df["JOB"].duplicated().sum()

np.int64(9)

In [ ]:
# if you want to drop duplicate values in particular column.
df.drop_duplicates("MOJ")

In [ ]:
# if you want to drop all the null values from the column 
df.dropna()

In [62]:
#if you want to create a new column with some operations then 

df.loc[(df["SAL"]<=2000),"GetsSAL"]="LowerSal"
df.loc[(df["SAL"]>=2000),"GetsSAL"]="HigherSal"
df

    EMPNO   ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO    GetsSAL
0    7369   SMITH      CLERK  7902  17-Dec-80   800     NaN      20   LowerSal
1    7499   ALLEN   SALESMAN  7698  20-Feb-81  1600   300.0      30   LowerSal
2    7521    WARD   SALESMAN  7698  22-Feb-81  1250   500.0      30   LowerSal
3    7566   JONES    MANAGER  7839  02-Apr-81  2975     NaN      20  HigherSal
4    7654  MARTIN   SALESMAN  7698  28-Sep-81  1250  1400.0      30   LowerSal
5    7698   BLAKE    MANAGER  7839  01-May-81  2850     NaN      30  HigherSal
6    7782   CLARK    MANAGER  7839  09-Jun-81  2450     NaN      10  HigherSal
7    7788   SCOTT    ANALYST  7566  19-Apr-87  3000     NaN      20  HigherSal
8    7839    KING  PRESIDENT     0  17-Nov-81  5000     NaN      10  HigherSal
9    7844  TURNER   SALESMAN  7698  08-Sep-81  1500     0.0      30   LowerSal
10   7876   ADAMS      CLERK  7788  23-May-87  1100     NaN      20   LowerSal
11   7900   JAMES      CLERK  7698  03-Dec-81   950     NaN      30   LowerSal
12   7902    FORD    ANALYST  7566  03-Dec-81  3000     NaN      20  HigherSal
13   7934  MILLER      CLERK  7782  23-Jan-82  1300     NaN      10   LowerSal

GroupBy In pandas

In [ ]:
# Use groupby function to group the columns 
J=df.groupby("JOB").agg({"JOB":"count"})
J

           JOB
JOB
ANALYST      2
CLERK        4
MANAGER      3
PRESIDENT    1
SALESMAN     4

In [65]:
gp=df.groupby(["JOB","GetsSAL"]).agg({"GetsSAL":"count"})
gp

                     GetsSAL
JOB       GetsSAL
ANALYST   HigherSal        2
CLERK     LowerSal         4
MANAGER   HigherSal        3
PRESIDENT HigherSal        1
SALESMAN  LowerSal         4

MERGE, JOIN AND CONCATENATE IN PANDAS

In [67]:
data1={
    "EMPID":["E01","E02","E03","E04","E05"],
    "Name":["Ram","Shyam","Mohan","Sohan","Raju"],
    "Age":[23,42,12,24,42]
}

data2={
    "EMPID":["E01","E02","E03","E04","E05"],
    "SAL":[45000,56000,43000,23000,50000]
}

d1=pd.DataFrame(data1)
d2=pd.DataFrame(data2)

In [ ]:
#Table 1
d1

  EMPID   Name  Age
0   E01    Ram   23
1   E02  Shyam   42
2   E03  Mohan   12
3   E04  Sohan   24
4   E05   Raju   42

In [ ]:
# Table 2
d2

  EMPID    SAL
0   E01  45000
1   E02  56000
2   E03  43000
3   E04  23000
4   E05  50000

In [72]:
# Now we are merging table 1 and 2 with the use of common table 
pd.merge(d1,d2,on="EMPID")

  EMPID   Name  Age    SAL
0   E01    Ram   23  45000
1   E02  Shyam   42  56000
2   E03  Mohan   12  43000
3   E04  Sohan   24  23000
4   E05   Raju   42  50000

In [ ]:
# Now we are joining both the table using left and right join according to the need.
pd.merge(left=d1,right=d2,on="EMPID",how="left")
pd.merge(left=d1,right=d2,on="EMPID",how="right")

  EMPID   Name  Age    SAL
0   E01    Ram   23  45000
1   E02  Shyam   42  56000
2   E03  Mohan   12  43000
3   E04  Sohan   24  23000
4   E05   Raju   42  50000

In [76]:
# Now we concatenate both the table 
pd.concat([d1,d2])

  EMPID   Name   Age      SAL
0   E01    Ram  23.0      NaN
1   E02  Shyam  42.0      NaN
2   E03  Mohan  12.0      NaN
3   E04  Sohan  24.0      NaN
4   E05   Raju  42.0      NaN
0   E01    NaN   NaN  45000.0
1   E02    NaN   NaN  56000.0
2   E03    NaN   NaN  43000.0
3   E04    NaN   NaN  23000.0
4   E05    NaN   NaN  50000.0