In [41]:
import numpy as np
import pandas as pd

In [42]:
ama=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Qspider\datasets\Data-Analysis-Datasets\Datasets-Practice\amazon_fires.csv",encoding="ISO-8859-1")

# Data cleaning operations

In [43]:
# see the information 
ama.info()
ama.head()

<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   str
 2   estado    6454 non-null   str
 3   numero    6322 non-null   str
 4   encontro  6454 non-null   str
dtypes: int64(1), str(4)
memory usage: 252.2 KB

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [44]:
# To rename a=the column name :
var={
    "ano":"year",
    "mes":"months",
    "estado":"state",
    "numero":"no_of_fires",
    "encontro":"date"
}

ama.rename(columns=var,inplace=True)

In [65]:
# TO replace the specific value form the dataset ;
ma={
    'Janeiro':"January",
    'Fevereiro':"February",
    'Março':"March",
    'Abril':"April",
    'Maio':"May",
    'Junho':"June",
    'Julho':"July",
    'Agosto':"August",
    'Setembro':"September",
    'Outubro':"October",
    'Novembro':"November",
    'Dezembro':"December"
}

ama["months"]=ama["months"].map(ma)

ama["months"].unique()

<StringArray>
[  'January',  'February',     'March',     'April',       'May',      'June',
      'July',    'August', 'September',   'October',  'November',  'December']
Length: 12, dtype: str

In [45]:
# Find how many null values are present.
ama["no_of_fires"].isnull().sum()

np.int64(132)

In [49]:
# find how many duplicates column in a dataset.
# ama.duplicated().sum()

ama.drop_duplicates(inplace=True)

In [ ]:
# To remove the fires from the no. of fires column 
ama["no_of_fires"]=ama["no_of_fires"].str.strip("Fires")

In [51]:
# replace  the data of no_of_fires from string to int
ama["no_of_fires"]=ama["no_of_fires"].astype(float)

In [ ]:
# To fill null values
med=round(ama["no_of_fires"].median())


ama["no_of_fires"]=ama["no_of_fires"].fillna(med)

In [60]:
ama["no_of_fires"]=ama["no_of_fires"].astype(int)

In [61]:
ama.head()

   year   months state  no_of_fires      date
0  1998  Janeiro  Acre            0  1/1/1998
1  1999  Janeiro  Acre            0  1/1/1999
2  2000  Janeiro  Acre            0  1/1/2000
3  2001  Janeiro  Acre            0  1/1/2001
4  2002  Janeiro  Acre            0  1/1/2002

In [68]:
# To set the index value :
# ama.set_index("no_of_fires")
ama.info()

<class 'pandas.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   months       6424 non-null   str
 2   state        6424 non-null   str
 3   no_of_fires  6424 non-null   int64
 4   date         6424 non-null   str
dtypes: int64(2), str(3)
memory usage: 301.1 KB