# Pandas 
#Features of Pandas :
1. Importing Datasets --> CSV, EXCEL,SQL ETC
2. Data Cleaning 
3. Size Mutability --> To add or remove the rows or columns
4. Reshaping and Pivoting the datasets 
5. Efficient Manipulation and Extraction.
6. Statstical Analysis

In [1]:
import pandas as pd
import numpy as np
# It is used in two ways 
# 1. Series  2. DataFrame

# Difference Between Series and Array 
--> Series:-  
1. Series belongs to Pandas. 
2. After the complex priority every datatype consider as Object.
3. It displays only data as well as index and datatype.
4. pd.Series(collection)

--> Array:-  
1. Array belongs to Numpy. 
2. After the string priority every datatype consider as Object.
3. It displays only data.
4. np.array(collection)

In [2]:
# Series : 
# syntax- var=pd.Series( Collection / Dictionary )

s=pd.Series([5,10,15,20,25])
s=pd.Series([5,10,15,20,25],index=["a","b","c","d","e"]) # we can change the values of index value using index argument.
s=pd.Series([5,10,15,20,25],index=["a","b","c","d","e"],name="Values")
s

a     5
b    10
c    15
d    20
e    25
Name: Values, dtype: int64

In [3]:
d={
    "name":["apple","orange"],
    "price":[12,23]
}

f={
    "Apple":250,
    "Orange":300,
    "Banana":450
}


n=["app","man","gra","oran"]
a=pd.Series(f)
# pd.Series(d)
v=pd.Series(n,index=["a","b","c","d"])
v["d"]
v["a"]
v["a"::]
v["d"::-1]
v[::]
v[::-1]

d    oran
c     gra
b     man
a     app
dtype: str

# Difference Between Series and DataFrame 

---> Series:-
1. 

---> DataFrame:-
1.

# Loc and iloc
 loc--> Label based indexing 
 iloc--> Location based indexing 

loc --> Label based indexing  
  syntax :  
        var.loc[index] -- > to access single value 
        var.loc[[index1,index2---indexN]]--> to access multiple values

iloc ---> Location based indexing 
  syntax :
        var.iloc[index] --> to access single value 
        var.iloc[[index1,index2,index3---indexN]] ---> To access multiple values

In [4]:
n=["app","man","gra","oran"]
a=pd.Series(n)
s=pd.Series(n,index=["a","b","c","d"])

# Loc method 
a.loc[[0,1,3]]
s.loc[["a","c","b","d"]]
a.loc[[1,3]]
s.loc[::-1]
s.loc["a"::2]
a.loc[0::2]
a.loc[::-1]

# iloc method 
a.iloc[0]
a.iloc[2]
a.iloc[[0,1,3,2]]
s.iloc[[3,1,0,2]]

d    oran
b     man
a     app
c     gra
dtype: str

# DataFrame

In [5]:
# DataFrame :  
# Syntax : var=pd.DataFrame(dictionary)

d={
    "Name":["Amandeep","Rahul","Mohan","Pankaj"],
    "ID":[1,3,2,4],
    "Salary":["5lpa","8lpa","3lpa","10lpa"]
}
df=pd.DataFrame(d)
df

       Name  ID Salary
0  Amandeep   1   5lpa
1     Rahul   3   8lpa
2     Mohan   2   3lpa
3    Pankaj   4  10lpa

In [6]:
# To add new column in existing DataFrame.
# Syntax : var["new_col_name"]=[equal number of values which are present in DF ]
df["Job"]=["sales","accountant","analyst","Finance"]
df["Blood_grouo"]=["A+","C+","Z-","L+"]
df

       Name  ID Salary         Job Blood_grouo
0  Amandeep   1   5lpa       sales          A+
1     Rahul   3   8lpa  accountant          C+
2     Mohan   2   3lpa     analyst          Z-
3    Pankaj   4  10lpa     Finance          L+

In [7]:
# To read the csv files.
# Syntax: var.pd.read_csv("file_path"/"file_name")

# Datasets to load 
# 1. Titanic 2. hr_data 3. winwquality 4. amazon_fires 5. Tips

# If you get UnicodeDecodeError---> encoding="ISO-8859-1"/"latin1"

titanic = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv")
hr_data = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv")
WineQuality = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv")
amazon_fires = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv",encoding="ISO-8859-1")
tips = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv")
tips

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
"""
var.head() --> It will display top 5 rows.
var.head(n) ---> It will display top n rows.
var.tail()---> It will display bottom 5 rows.
var.tail(n)---> It will display bottom n rows.
var.info() ---> It will display the overall information about Dataframe.
var.shape() ---> It will return number of rows and columns present in the DF.
var.describe() --> It will return the statistical information about DataFrame, It will work only on numeric columns.
var.describe(include=object) --> It will return the non-statistical information about Dataframe
var.describe(include=all) ---> It will return all the information about Dataframe.


var.sample() ---> It will take a single row as a sample.
var.sample(n) ---> It will take a n no. of row as a sample.
var["column_name].unique() ---> It will return the unique values present in the column.
var["column_name].value_counts() ---> It will return the occurance of unique values.
var.sort_values(by="col_name,ascending=False) ---> It sort the  dataframe according to the given value, ascending =False is used for descending order.
var.columns ---> It will return the column names 
"""

# titanic.info()
# hr_data.info()
# tips.shape
# hr_data.shape
# tips.describe()
# tips.describe(include="object")
tips.sample()
tips.sample(4)
tips["tip"].unique()
tips["tip"].value_counts()
tips.sort_values(by="tip")
tips.columns

     Unnamed: 0  total_bill    tip     sex smoker   day    time  size
92           92        5.75   1.00  Female    Yes   Fri  Dinner     2
111         111        7.25   1.00  Female     No   Sat  Dinner     1
67           67        3.07   1.00  Female    Yes   Sat  Dinner     1
236         236       12.60   1.00    Male    Yes   Sat  Dinner     2
0             0       16.99   1.01  Female     No   Sun  Dinner     2
..          ...         ...    ...     ...    ...   ...     ...   ...
141         141       34.30   6.70    Male     No  Thur   Lunch     6
59           59       48.27   6.73    Male     No   Sat  Dinner     4
23           23       39.42   7.58    Male     No   Sat  Dinner     4
212         212       48.33   9.00    Male     No   Sat  Dinner     4
170         170       50.81  10.00    Male    Yes   Sat  Dinner     3

[244 rows x 8 columns]

In [ ]:
# Indexing and Slicing on Data
# loc and iloc 

# loc --> label based indexing 
  # 1. var.loc[index] or var.loc[index,"col_name"]
  # 2. var.loc[[index1,index2---indexN]] or var.loc[[index1,index2---indexN],[col1,col2---colN]]
  # 3. var.loc[sv:ev:up]
  # 4. var.loc[sv:ev:up,"col_name"] or var.loc[sv:ev:up,[col1,col2---colN]]


tips.loc[1]
tips.loc[[1,2,4,5]]
tips.loc[1::3]
tips.loc[::-1,["tip","smoker","day"]]

#iloc ---> Location based indexing 
   # 1. var.iloc[index]
   # 2. var.iloc[[index1, index2---indexN]] or var.iloc[[index1,index2---indexN],[col_index1,col_index2----col_indexN]]
   # 3. var.iloc[sv:ev:up]
   # 4. var.iloc[sv:ev:up,[col_index1, col_index2---col_indexN]]
   # 5. var.iloc[sv:ev:up,sv:ev:up]
                # row  slice, calumn slice

tips.iloc[1]
tips.iloc[[1,2,5,9],[1,3,4]] # we are not giving here column name , if you want to take column just give column index value.
tips.iloc[0:8,[1,2,3]]

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4
5           5       25.29  4.71    Male     No  Sun  Dinner     4
6           6        8.77  2.00    Male     No  Sun  Dinner     2
7           7       26.88  3.12    Male     No  Sun  Dinner     4
8           8       15.04  1.96    Male     No  Sun  Dinner     2

# Difference between loc and iloc in DataFrame

In [89]:
# Aggregation Function : 
# 1. sum() ---> Sum of all the values present in the column
# 2. min() ---> Minimumn value present in the column 
# 3. max() ---> Maximum value present in the column 
# 4. mean() ---> Average value
# 5. mode() ---> most frequent value 
# 6. median() ---> middle value after sorting into ascending 
# 7. count() ---> count of values 

# Syntax to apply aggregation function:
        # var["col_name"].fname()

tips["total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
# titanic 
# hr_data 
# WineQuality 
# amazon_fires 

# what it the total revenue in tips dataset.
tips["total_bill"].sum()   


# What is the average age of travellers who were traveling in titanic ?
titanic["age"].mean()   


# what was the highest tip given by customer ?
tips["tip"].max()   


# what is the average number of projects in hr ?
hr_data["number_project"].mean()   


# what is the average wine quality ?
WineQuality["quality"].mean()   


# count of travelers travelling in titanic
titanic["sex"].count()   


# Total number of project in hr
hr_data["number_project"].sum()   


# the number of employees who left the company 
hr_data["left"].sum()   


# Total number traverls who servived.
titanic["survived"].sum()   


# Average pH level of alcohol 
WineQuality["pH"].mean()

np.float64(3.218395499383477)

np.int64(1309)