In [1]:
import numpy as np
import pandas as pd

In [2]:
cna=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Qspider\datasets\Data-Analysis-Datasets\Datasets-Cleaning\uncleaned_appliances.csv",encoding="latin1")
# cna.head()
# cna.info()

In [3]:
cna.duplicated().sum() # 209

np.int64(209)

In [4]:
cna.drop_duplicates(inplace=True) # drop all duplicates value

In [5]:
cna.duplicated().sum() # There is  no dupulicate value in the dataset.

np.int64(0)

In [6]:
cna

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN
...,...,...,...,...,...,...,...,...
3981,NaN,NaN,NaN,NaN,$54.34,NaN,NaN,Unbeatablesale 142Mhz .25 Wave Kulduckie
3982,NaN,NaN,NaN,NaN,$64.06,NaN,NaN,Unbeatablesale 440-460Mhz Load And Tip Only -B...
3983,NaN,NaN,NaN,NaN,$61.99,-24%,NaN,"TaoTronics Air Fryer, 1700W 14.8 QT, 9 In 1 Ai..."
3984,NaN,NaN,NaN,NaN,$81.47,-3%,NaN,"Air Fryer 5.3 Quart, Digital Oilless Frying Co..."
3985,NaN,NaN,NaN,NaN,$501.21,-28%,NaN,Up To 350lbs Okin Motor Power Lift Recliner Ch...

In [7]:
# d={"goods-title-link--jump":"Goods_Title_Link_Jump"}
# cna.rename(columns=d,inplace=True)

In [8]:
# to remove unwanted columns
"""cna.drop(cna.columns[[1,0]],axis=1,inplace=True)
cna.drop("goods-title-link",axis=1,inplace=True)"""


# to remvoe  the # and best seller from the rank-title column
"""cna["rank-title"]=cna["rank-title"].str.strip("# Best Sellers")"""


# convert the datatype into another datatype
"""cna["rank-title"]=cna["rank-title"].astype("float")"""


# sum of all null values in rank-title columns 
"""cna["rank-title"].isna().sum()"""


# cna["rank-title"].unique()

# find the average value of rank-title and replace all null values with the average value
"""m=round(cna["rank-title"].mean(),2)
# cna["rank-title"]=cna["rank-title"].fillna(m)"""

'm=round(cna["rank-title"].mean(),2)\n# cna["rank-title"]=cna["rank-title"].fillna(m)'

In [9]:

# to remove in from the rank-sub column and replace null value with most repeated  value in rank-sub column.
"""cna["rank-sub"]=cna["rank-sub"].str.strip("in")
# ran=cna["rank-sub"].mode()
# cna["rank-sub"]=cna["rank-sub"].fillna("Hair Dryers")"""
# cna["rank-sub"].value_counts()


# Now , convert currency from dollar to rupee with the sign 
"""
cna["price"]=cna["price"].str.strip("$ ,")
cna["price"]=cna["price"].str.replace(",", "")
cna["price"]=cna["price"].astype(float)
cna["price"]=cna["price"]*96
cna["price"]=cna["price"].astype(str)
cna["price"]="₹"+cna["price"]
cna["price"].unique()
"""

cna

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN
...,...,...,...,...,...,...,...,...
3981,NaN,NaN,NaN,NaN,$54.34,NaN,NaN,Unbeatablesale 142Mhz .25 Wave Kulduckie
3982,NaN,NaN,NaN,NaN,$64.06,NaN,NaN,Unbeatablesale 440-460Mhz Load And Tip Only -B...
3983,NaN,NaN,NaN,NaN,$61.99,-24%,NaN,"TaoTronics Air Fryer, 1700W 14.8 QT, 9 In 1 Ai..."
3984,NaN,NaN,NaN,NaN,$81.47,-3%,NaN,"Air Fryer 5.3 Quart, Digital Oilless Frying Co..."
3985,NaN,NaN,NaN,NaN,$501.21,-28%,NaN,Up To 350lbs Okin Motor Power Lift Recliner Ch...